version: '3'
services:
   cloud-config-server:
      container_name: cloud-config-server
      image: 167.86.83.61:5000/cloud-config-server
      build:
         context: ../../cloud-config-server
         dockerfile: ../docker-assembly/cloud/Dockerfile-cloud-config-server
      volumes:
         - /opt/cloud/config:/opt/cloud/config     
      ports:
         - 6091:6091
      networks:
         - social-cloud-network
      deploy:
         placement:
            constraints: [node.labels.deploy_server == true]
   cloud-gateway-server:
      container_name: cloud-gateway-server
      image: 167.86.83.61:5000/cloud-gateway-server
      build:
         context: ../../cloud-gateway-server
         dockerfile: ../docker-assembly/cloud/Dockerfile-cloud-gateway-server
      ports:
      - 6092:6092
      networks:
      - social-cloud-network
   nlp-server:
      container_name: nlp-server
      image: 167.86.83.61:5000/nlp-server
      build:
         context: ../../nlp-server
         dockerfile: ../docker-assembly/cloud/Dockerfile-nlp-server
      ports:
         - 6082:6082
      volumes:
         - /opt/cloud/nlp-models:/opt/cloud/nlp-models
      networks:
         - social-cloud-network
   data-pusher:
      container_name: data-pusher
      image: 167.86.83.61:5000/data-pusher
      build:
         context: ../../data-pusher
         dockerfile: ../docker-assembly/cloud/Dockerfile-data-pusher
      ports:
         - 6081:6081
         - 61616:61616
      networks:
         - social-cloud-network
networks:
   social-cloud-network: