server:
   port: 6092
routes:
   nlp-server: http://localhost:6082
   data-pusher: http://localhost:6081	
app:
   version: 0.0.1

management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway

   