server:
   port: 6082
app:
   version: 0.0.2
models :
   word2vec: /home/antonio/git/social-platform/nlp-trained-models/word2vec.dat
   rnn: /home/antonio/git/social-platform/nlp-trained-models/network.dat